/* JOIN */
SELECT * FROM EMPLOYESS A, DEPARTMENTS B WHERE A.DEPARTEMENT_ID = B.DEPARTEMENT_ID;

SELECT A.EMPLOYEE_ID, A.DEPARTMENT_ID, B.DEPARTMENT_NAME, C.LOCATION_ID, C.CITY
FROM EMPLOYEES A, DEPARTMENTS B, LOCATIONS C
WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID AND B.LOCATION_ID = C.LOCATION_ID;

SELECT COUNT(*) FROM EMPLOYEES A, DEPARTMENTS B WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID;
SELECT COUNT(*) FROM EMPLOYEES;

/* SELF JOIN */
SELECT A.EMPLOYEE_ID, A.FIRST_NAME, A.LAST_NAME, A.MANAGER_ID, B.FIRST_NAME || ' ' || B.LAST_NAME AS MANAGER_NAME
FROM EMPLOYEES A, EMPLOYEES B WHERE A.MANAGER_ID = B.MANAGER_ID;