/* DDL */

--테이블 생성
CREATE TABLE SAMPLE_PRODUCT (
    PROD_ID NUMBER,
    PROD_NAME VARCHAR2(30),
    PROD_MAKE_DATE DATE DEFAULT SYSDATE
);

DROP TABLE SAMPLE_PRODUCT;
--값 추가
INSERT INTO SAMPLE_PRODUCT VALUES(1, 'TELEVISION', TO_DATE('211005','YYMMDD'));
INSERT INTO SAMPLE_PRODUCT VALUES(2, 'WASHER', TO_DATE('201221','YYMMDD'));
INSERT INTO SAMPLE_PRODUCT VALUES(3, 'CLEANER', TO_DATE('180203','YYMMDD'));

--확인
SELECT * FROM SAMPLE_PRODUCT;

--값 수정 (열 추가)
ALTER TABLE SAMPLE_PRODUCT ADD(
    FACTORY VARCHAR2(10)
);

--값 수정 (열 수정)
ALTER TABLE SAMPLE_PRODUCT MODIFY(
    FACTORY CHAR(10)
);

--값 수정 (열 이름 변경)
ALTER TABLE SAMPLE_PRODUCT RENAME COLUMN FACTORY TO FACTORY_NAME;

--값 수정 (열 삭제)
ALTER TABLE SAMPLE_PRODUCT DROP COLUMN FACTORY_NAME;

--값 수정 (데이터 전체 삭제)
TRUNCATE TABLE SAMPLE_PRODUCT;
DELETE FROM SAMPLE_PRODUCT;

--테이블 삭제
DROP TABLE SAMPLE_PRODUCT;

SELECT * FROM SAMPLE_PRODUCT;











