/* TABLE 생성해보기 */
--테이블명 : SAMPLE
--DEPTNO : NUMBER(20)
--DEPTNAME : VARCHAR2(15)
--DEPTLOC : VARCHAR2(15)
--DPETMANAGER : VARCHAR2(10)
CREATE TABLE SAMPLE(
	DEPTNO NUMBER(20),
	DEPTNAME VARCHAR2(15),
	DEPTLOC VARCHAR2 (15),
	DEPTMANAGER VARCHAR2(10)
);

/* 테이블에 값 넣기 */
INSERT INTO SAMPLE VALUES(10, '기획실', '부산', '홍길동');
INSERT INTO SAMPLE VALUES(20, '전산실', '서울', '김말똥');
INSERT INTO SAMPLE (DEPTNO, DEPTNAME, DEPTLOC) VALUES(30, '영업부실', '광주');

/* 테이블 값 수정하기 */
--SAMPLE 에서 DEPTNO가 30인 부서번호를 50으로 수정
UPDATE SAMPLE SET DEPTNO = 50 WHERE DEPTNO = 30;

--SAMPLE 에서 DEPTNAME 영업부인 DEPTLOC를 인천으로 수정
UPDATE SAMPLE SET DEPTLOC = '인천' WHERE DEPTNAME = '영업부실';

--DELETE 
DELETE  SAMPLE WHERE DEPTNAME = '기획실';
DELETE SAMPLE WHERE DEPTNAME = '전산실';
SELECT * FROM SAMPLE;

ROLLBACK;
COMMIT;


/* 제약조건 */
--NOT NULL
CREATE TABLE NULL_TEST (
	COL1 VARCHAR2(20) NOT NULL,
	COL2 VARCHAR2(20)
);

CREATE TABLE NULL_TEST2 (
	COL1 VARCHAR2(20) NOT NULL,
	COL2 VARCHAR2(20) NULL,
	COL3 VARCHAR2(20)
);

INSERT INTO NULL_TEST (COL1, COL2) VALUES('AA','BB');
SELECT * FROM NULL_TEST;

INSERT INTO NULL_TEST VALUES (NULL, 'BB');

INSERT INTO NULL_TEST (COL1, COL2) VALUES('AA',NULL);
SELECT * FROM NULL_TEST;


--UNIQUE
CREATE TABLE UNIQUE_TEST(
	COL1 VARCHAR2(20) UNIQUE NOT NULL,
	COL2 VARCHAR2(20) UNIQUE,
	COL3 VARCHAR2(20)
);

INSERT INTO UNIQUE_TEST (COL1, COL2, COL3) VALUES ('AA', 'BB', 'CC');
INSERT INTO UNIQUE_TEST (COL1, COL2, COL3) VALUES ('AA1', 'BB1', 'CC1');

--무결성 깨짐
UPDATE UNIQUE_TEST SET COL1 = 'AA' WHERE COL2 = 'BB1';

INSERT INTO UNIQUE_TEST (COL1, COL2, COL3) VALUES ('AA2', 'BB2', 'CC2');
INSERT INTO UNIQUE_TEST (COL1, COL2, COL3) VALUES ('AA3', NULL, 'CC3');
SELECT * FROM UNIQUE_TEST ;


--CHECK
CREATE TABLE CHECK_TEST3(
	GENDER VARCHAR2(10) NOT NULL CONSTRAINTS CHECK_GENDER3 CHECK (GENDER IN ('M', 'F','남자','여자'))
);

INSERT INTO CHECK_TEST3 VALUES ('F');
INSERT INTO CHECK_TEST3 VALUES ('남자');
SELECT * FROM CHECK_TEST3;



