/* 서브쿼리 QUIZ */

--QUIZ #1 : EMPLOYEES 테이블에서 급여의 평균보다 작은 사원의 사원번호, 이름, 담당업무, 급여, 부서번호를 조회
SELECT E.EMPLOYEE_ID , E.FIRST_NAME || ' ' || E.LAST_NAME "NAME", E.JOB_ID , J.JOB_TITLE , E.SALARY , E.DEPARTMENT_ID 
FROM EMPLOYEES E INNER JOIN JOBS J ON J.JOB_ID = E.JOB_ID 
WHERE E.SALARY < (SELECT AVG(E2.SALARY) FROM EMPLOYEES E2);

--QUIZ #2 : EMPLOYEES 테이블에서 100번 부서의 최소 급여보다 최소급여가 많은 다른 모든 부서를 조회
SELECT E.DEPARTMENT_ID, MIN(SALARY)  FROM EMPLOYEES E GROUP BY E.DEPARTMENT_ID 
HAVING MIN(E.SALARY) > (SELECT MIN(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID = '100');

--QUIZ #3 : EMPLOYEES 테이블에서 가장 많은 사원을 갖는 MANAGER의 사원번호를 조회
SELECT MANAGER_ID FROM EMPLOYEES E GROUP BY E.MANAGER_ID 
HAVING COUNT(*) = (SELECT MAX(COUNT(*)) FROM EMPLOYEES E2 GROUP BY E2.MANAGER_ID) ;

--QUIZ #4 : EMPLOYEES 테이블에서 가장 많은 사원이 속해있는 부서번호와 사원수 조회
SELECT E.DEPARTMENT_ID, COUNT(*)  FROM EMPLOYEES E GROUP BY E.DEPARTMENT_ID 
HAVING COUNT(*) = (SELECT MAX(COUNT(EMPLOYEE_ID)) FROM EMPLOYEES GROUP BY DEPARTMENT_ID) ;

--QUIZ #5 : EMPLOYEES 테이블에서 사워번호가 123인 사원의 직업과 같고, 사원번호가 192인 사원의 급여보다 많은 사원의 사원번호, 이름, 급여 조회
SELECT E.EMPLOYEE_ID , E.LAST_NAME || ' ' || E.FIRST_NAME "NAME" , E.SALARY FROM EMPLOYEES E
WHERE (E.JOB_ID = (SELECT JOB_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = '123')) 
AND (E.SALARY > (SELECT SALARY FROM EMPLOYEES WHERE EMPLOYEE_ID = '192'));



/*
 * 
 * SELECT    e.DEPARTMENT_ID , d.DEPARTMENT_NAME, 
      COUNT(*) , sum(SALARY) ,
      l.CITY 
FROM   EMPLOYEES e 
   INNER JOIN DEPARTMENTS d 
   ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
   INNER JOIN LOCATIONS l 
   ON d.LOCATION_ID = l.LOCATION_ID 
WHERE d.DEPARTMENT_ID IN (10, 30, 100, 110)   
GROUP BY e.DEPARTMENT_ID, d.DEPARTMENT_NAME, l.CITY 
HAVING d.DEPARTMENT_NAME IN ('Administration', 'Accounting')
;
 * 
 * 
 * 
 * */

--==================================================================================

/* DDL */
--CREATE 로 테이블 생성
CREATE TABLE EMPLOYEES2 (
	EMPLOYEE_ID NUMBER(10),
	NAME VARCHAR2(20),
	SALARY NUMBER(7,2)
);

--기존 테이블과 동일하게 작성
CREATE TABLE EMPLOYEES3 AS SELECT * FROM EMPLOYEES2;

--컬럼추가
ALTER TABLE EMPLOYEES2 ADD(
	MANAGER_ID VARCHAR2(10)
);

--컬럼 변
ALTER TABLE EMPLOYEES2 MODIFY(
	MANAGER_ID VARCHAR2(20)
);

--컬럼삭제
ALTER TABLE EMPLOYEES2 DROP (
	MANAGER_ID
);

--데이터 삽입
INSERT INTO EMPLOYEES2 VALUES(1, '테스트', 30000);

--데이터 전체 삭제
TRUNCATE TABLE MPLOYEES2;

--테이블 삭제
DROP TABLE EMPLOYEES2 ;
