/* PRIMARY KEY */
CREATE TABLE PRIMARY_TEST(
	STUDENT_ID NUMBER(10) PRIMARY KEY,
	NAME VARCHAR2(20)
);

CREATE TABLE PRIMARY_TEST2(
	STUDENT_ID NUMBER(10),
	NAME VARCHAR2(20),
	CONSTRAINTS STUDENT_PK PRIMARY KEY (STUDENT_ID)
);

CREATE TABLE PRIMARY_TEST3(
	STUDENT_ID NUMBER(10),
	NAME VARCHAR2(20)
);

--테이블을 생성하고 나서 이후에 기본키를 생성하는 방법
ALTER TABLE PRIMARY_TEST3 ADD CONSTRAINTS STUDENT_PK3 PRIMARY KEY (STUDENT_ID);


CREATE TABLE DADDY(
	IDX NUMBER(10),
	mID NUMBER(10) PRIMARY KEY
);

CREATE TABLE DAUGHTER(
	INDX NUMBER(10) PRIMARY KEY,
	mID NUMBER(10),
	CONSTRAINTS FK_DA FOREIGN KEY(mID) REFERENCES DADDY(mID) ON DELETE CASCADE
);

INSERT INTO DADDY VALUES(1, 10);
INSERT INTO DADDY VALUES(2, 20);

INSERT INTO DAUGHTER VALUES(100, 10);
INSERT INTO DAUGHTER VALUES(101, 10);
INSERT INTO DAUGHTER VALUES(102, 10);
INSERT INTO DAUGHTER VALUES(200, 20);
INSERT INTO DAUGHTER VALUES(300, 30);

SELECT * FROM DAUGHTER;

DELETE FROM DAUGHTER WHERE INDX = 100;

DELETE FROM DADDY WHERE IDX = 1;



CREATE TABLE DADDY2(
	IDX NUMBER(10),
	mID NUMBER(10) PRIMARY KEY
);

CREATE TABLE DAUGHTER2(
	INDX NUMBER(10) PRIMARY KEY,
	mID NUMBER(10),
	CONSTRAINTS FK_DA2 FOREIGN KEY(mID) REFERENCES DADDY2(mID) ON DELETE SET NULL
);


INSERT INTO DADDY2 VALUES(1, 10);
INSERT INTO DADDY2 VALUES(2, 20);

INSERT INTO DAUGHTER2 VALUES(100, 10);
INSERT INTO DAUGHTER2 VALUES(101, 10);
INSERT INTO DAUGHTER2 VALUES(102, 10);
INSERT INTO DAUGHTER2 VALUES(200, 20);

DELETE FROM DADDY2 WHERE IDX = 1;

SELECT * FROM DAUGHTER2;
