/* 변환함수 */
--암묵적 형변환
SELECT 1 + '1' FROM DUAL;


--TO_CHAR()
SELECT TO_CHAR(SYSDATE, 'YY'), TO_CHAR(SYSDATE, 'MM'), TO_CHAR(SYSDATE, 'DD') FROM DUAL; 

--TO_NUMBER()
SELECT TO_NUMBER('123') FROM DUAL;

--TO_DATE()
SELECT TO_DATE('20211001' , 'YYMMDD') AS TODAY FROM DUAL;


/* NOT NULL 처리 */
SELECT * FROM EMPLOYEES ORDER BY COMMISSION_PCT;
SELECT * FROM EMPLOYEES WHERE commission_pct IS NOT NULL;

SELECT SALARY * COMMISSION_PCT FROM EMPLOYEES; --COMMISSION_PCT가 NULL이면 계산불가
SELECT SALARY * COMMISSION_PCT AS RESULT FROM EMPLOYEES WHERE COMMISSION_PCT IS NOT NULL; --NULL 계산 안하기
SELECT SALARY * NVL(COMMISSION_PCT,0.5) FROM EMPLOYEES ORDER BY COMMISSION_PCT; --NULL대체하기



/* DECODE */
SELECT * FROM EMPLOYEES;

SELECT FIRST_NAME, SALARY, DEPARTMENT_ID, DECODE(DEPARTMENT_ID, 60, SALARY*1.1 , SALARY) AS "60 DEPARTMENT_ID", 
DECODE(DEPARTMENT_ID, 60, '10% UP', 'NONE') FROM EMPLOYEES;


/* CASE */
SELECT * FROM EMPLOYEES;












