/* 확인용 */
SELECT * FROM EMPLOYEES;

/* 문자 관련 함수 */
--REPLACE
SELECT JOB_ID, REPLACE(JOB_ID, 'ACCOUNT', 'ACCNT') FROM EMPLOYEES;

--LPAD, RPAD
SELECT FIRST_NAME, LPAD(FIRST_NAME, 12, ' ') FROM EMPLOYEES;
SELECT FIRST_NAME, RPAD(FIRST_NAME, 12, ' ') FROM EMPLOYEES;

--LTRIM, RTRIM
SELECT JOB_ID, LTRIM(JOB_ID, 'F'), RTRIM(JOB_ID, 'T') FROM EMPLOYEES;
SELECT JOB_ID, LTRIM(LPAD(FIRST_NAME, 12, '-'), '-') FROM EMPLOYEES;

--TRIM
SELECT TRIM('      -SPACE-     ') FROM DUAL;


/* 숫자관련 함수 */
--ROUND()
SELECT SALARY, (SALARY/30) SALARY FROM EMPLOYEES;
SELECT SALARY, ROUND(SALARY/30, 0) AS "SALARY1", ROUND(SALARY/30,1) AS SALARY2, ROUND(SALARY/30,-1) SALARY3 FROM EMPLOYEES;






