SELECT * FROM EMPLOYEES;

/* VIEW */
--VIEW 만들기
CREATE VIEW V_EMP(
	EMP_ID, FIRST_NAME, JOB_ID, HIREDATE, DEPT_ID
) AS SELECT EMPLOYEE_ID, FIRST_NAME, JOB_ID, HIRE_DATE, DEPARTMENT_ID FROM EMPLOYEES WHERE JOB_ID='ST_CLERK';

SELECT * FROM V_EMP;


--수정 가능한 VIEW만들기
CREATE OR REPLACE VIEW V_EMP2(
	EMP_ID, FIRST_NAME, JOB_ID, HIREDATE, DEPT_ID
) AS SELECT NVL(E.EMPLOYEE_ID , NULL), NVL(FIRST_NAME,NULL), E.JOB_ID , E.HIRE_DATE , E.DEPARTMENT_ID FROM EMPLOYEES E WHERE E.JOB_ID ='SH_CLERK';  

SELECT * FROM V_EMP2;

--V_EMP 수정
UPDATE V_EMP SET FIRST_NAME='KIM' WHERE FIRST_NAME ='Julia';
UPDATE V_EMP2 SET FIRST_NAME='KIM' WHERE FIRST_NAME ='Julia'; --NVL함수가 들어갔으므로 UPDATE불가

--VIEW 활용목적 확인하기
CREATE OR REPLACE VIEW V_EMP_SALARY(
	EMP_ID, LAST_NAME, SALARY, TOTAL_SAL
) AS SELECT EMPLOYEE_ID, LAST_NAME, SALARY, (SALARY + NVL(COMMISSION_PCT, 0))*12 FROM EMPLOYEES;

SELECT * FROM V_EMP_SALARY;

CREATE VIEW V_EMP3 (
	EMP_ID, NAME, DEPARTMENT_ID, HIRE_DATE 
) AS SELECT EMPLOYEE_ID , FIRST_NAME || ' ' || LAST_NAME, DEPARTMENT_ID, HIRE_DATE FROM EMPLOYEES WHERE DEPARTMENT_ID = 50;

SELECT * FROM V_EMP3;


/* 시퀀스 */
--제품번호 생성하는 시퀀스 만들기
CREATE SEQUENCE SEQ_SERIAL_NO
	INCREMENT BY 1
	START WITH 100
	MAXVALUE 110
	MINVALUE 99
	CYCLE 
	CACHE 2;

--SEQ 활용할 테이블
CREATE TABLE GOOD(
	GOOD_NO NUMBER(3),
	GOOD_NAME VARCHAR2(10)
);

--NEXTVAL 확인
INSERT INTO GOOD VALUES (SEQ_SERIAL_NO.NEXTVAL, '제품1');
SELECT * FROM GOOD;

SELECT SEQ_SERIAL_NO.CURRVAL FROM DUAL;

--CURRVAL 확인
INSERT INTO GOOD VALUES (SEQ_SERIAL_NO.CURRVAL, '제품2');
SELECT * FROM GOOD;


--시퀀스 삭제하기
CREATE SEQUENCE SEQ_SERIAL_NO2
	INCREMENT BY 1
	START WITH 100
	MAXVALUE 110
	MINVALUE 99
	CYCLE 
	CACHE 2;

DROP SEQUENCE SEQ_SERIAL_NO2;

