SELECT * FROM EMPLOYEES e ;

/* 함수 */
-- NVL 
SELECT E.FIRST_NAME , E.LAST_NAME , NVL(E.COMMISSION_PCT , 0) FROM EMPLOYEES E; 

--DECODE
SELECT D.DEPARTMENT_ID ,DECODE(D.DEPARTMENT_ID, 20, 'MA', 60, 'IT', 90, 'EX', 'ETC') FROM DEPARTMENTS D;

--CASE
SELECT E.FIRST_NAME, E.DEPARTMENT_ID , 
CASE 
WHEN E.DEPARTMENT_ID = 20 THEN 'MA' 
WHEN E.DEPARTMENT_ID = 60 THEN 'IT'
ELSE ''
END "DEPARTMENT"
FROM EMPLOYEES E;

--DISTINCT, GROUP BY
SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES E;
SELECT E.DEPARTMENT_ID FROM EMPLOYEES E GROUP BY DEPARTMENT_ID ;

--부서별 급여합계
SELECT SUM(SALARY), DEPARTMENT_ID FROM EMPLOYEES E GROUP BY DEPARTMENT_ID ;
--SELECT DISTINCT E.DEPARTMENT_ID , SUM(SALARY) FROM EMPLOYEES E;  --요건 에러나는 경우

--부서별 사원 수와 평균 급여, 급여의 합을 구해보자
SELECT COUNT(E.SALARY) "사원수", AVG(E.SALARY) "평균",SUM(E.SALARY) "총급여" FROM EMPLOYEES E GROUP BY E.DEPARTMENT_ID ;

--부서별, 직급별 사원수, 평균 급여, 급여합
SELECT E.DEPARTMENT_ID , E.JOB_ID ,COUNT(E.SALARY), AVG(E.SALARY) , SUM(E.SALARY) 
FROM EMPLOYEES E GROUP BY E.DEPARTMENT_ID , E.JOB_ID ORDER BY E.DEPARTMENT_ID;

--위의 코드에서 WHERE절 추가

SELECT E.DEPARTMENT_ID , E.JOB_ID ,COUNT(E.SALARY), AVG(E.SALARY) , SUM(E.SALARY) 
FROM EMPLOYEES E WHERE DEPARTMENT_ID = 80 GROUP BY E.DEPARTMENT_ID , E.JOB_ID ORDER BY E.DEPARTMENT_ID;

--HAVING
SELECT E.DEPARTMENT_ID , COUNT(*) FROM EMPLOYEES E WHERE E.DEPARTMENT_ID IS NOT NULL GROUP BY E.DEPARTMENT_ID HAVING COUNT(*) >= 10;


/* 문제 */
SELECT * FROM EMPLOYEES E;
--QUIZ #1 : EMPLOYEES 테이블에서 JOBID가 SA로 시작하는 사람에 대하여 급여의 평균, 최고액, 최저액, 합계를 구하여 출력하라
SELECT AVG(E.SALARY) AS "평균 급여", MAX(E.SALARY) AS "최고급여", MIN(E.SALARY) "최저급여", SUM(E.SALARY) "급여합계" 
FROM EMPLOYEES E WHERE E.JOB_ID LIKE('SA%');

--QUIZ #2 : EMPLOYEES 에서 각 부서별로 인원수, 급여의 평균, 최저급여, 최고급여, 급여의 합을 구하여 급여의 합이 많은 순으로 출력하라
SELECT COUNT(E.JOB_ID) "부서별 인원" , AVG(E.SALARY) "평균 급여", MIN(E.SALARY) "최저급여", MAX(E.SALARY) "최고급여", SUM(E.SALARY) "급여 총합"
FROM EMPLOYEES E GROUP BY E.DEPARTMENT_ID ORDER BY SUM(E.SALARY) DESC;

--QUIZ #3 : EMPLOYEES에서 부서별, 업무별 그룹하여 결과를 부서번호, 업무, 인원수, 급여의 평균, 급여의 합을 구하여 출력하라
SELECT E.DEPARTMENT_ID "부서번호", E.JOB_ID "업무", COUNT(*) "인원수", AVG(E.SALARY) "평균 급여", SUM(E.SALARY) "급여 총합"
FROM EMPLOYEES E GROUP BY E.DEPARTMENT_ID, E.JOB_ID ;

--QUIZ #4 : EMPLOYEES 에서 부서 인원이 4보다 많은 부서의 부서번호, 인원수, 급여의 합을 구하여 출력하라
SELECT E.DEPARTMENT_ID "부서번호", COUNT(*) "인원수", SUM(E.SALARY) "급여 총합"
FROM EMPLOYEES E GROUP BY E.DEPARTMENT_ID HAVING COUNT(*) > 4; 

--QUIZ #5 : EMPLOYEES 에서 급여가 최대 10000-이상인 부서에 대해서 부서번호, 평균급여, 급여의 합계를 구하여 출력하라
SELECT E.DEPARTMENT_ID "부서번호", AVG(E.SALARY) "평균 급여", SUM(E.SALARY) "급여 총합"
FROM EMPLOYEES E GROUP BY E.DEPARTMENT_ID HAVING MAX(E.SALARY) >= 10000;


