
/* EMPLOYEES 테이블 QUIZs */
--QUIZ #1 : 연봉이 12000이상인 직원들의 LASTNAME과 연봉 조회
SELECT E.LAST_NAME, E.SALARY FROM EMPLOYEES E WHERE E.SALARY >= 12000;

--QUIZ #2 : 사원번호가 176인 사람의 LASTNAME과 부서번호를 조회
SELECT E.LAST_NAME , E.DEPARTMENT_ID FROM EMPLOYEES E WHERE EMPLOYEE_ID = 176;

--QUIZ #3 : 연봉이 5000에서 12000인 범위 이외의 사람들의 LASTNAME , 연봉 조회
SELECT E.LAST_NAME , E.SALARY FROM EMPLOYEES E WHERE NOT E.SALARY BETWEEN 5000 AND 12000;

--QUIZ #4 : 20번 및 50번 부서 근무자의 LASTNAME및 부서번호를 안파벳순으로 조회
SELECT E.LAST_NAME , E.DEPARTMENT_ID FROM EMPLOYEES E WHERE E.DEPARTMENT_ID IN (20, 50) ORDER BY LAST_NAME ;

--QUIZ #5 : 20번 및 50번 부서에 근무하며 연봉이 5000~12000인 사원의 LASTNAME 및 연봉 조회
SELECT E.LAST_NAME , E.SALARY FROM EMPLOYEES E WHERE (E.SALARY BETWEEN 5000 AND 12000) AND E.DEPARTMENT_ID IN (20, 50);

--QUIZ #6 : 매니저가 없는 사람들의 LASTNAME 및 JOBID를 조회한다.
SELECT E.LAST_NAME , E.JOB_ID FROM EMPLOYEES E WHERE MANAGER_ID IS NULL;

--QUIZ #7 : 커미션을 버는 모든 사원들의 LASTNAME, 연봉 및 커미션 조회 (연봉 역순)
SELECT E.LAST_NAME , E.SALARY , E.COMMISSION_PCT FROM EMPLOYEES E WHERE COMMISSION_PCT IS NOT NULL ORDER BY E.COMMISSION_PCT DESC;

--QUIZ #8 : LASTNAME의 첫글자가 A인 사람들의 LATNAME을 조회
SELECT E.LAST_NAME FROM EMPLOYEES E WHERE E.LAST_NAME LIKE 'A%';


/* 함수 */
--CONCAT
SELECT CONCAT('HELLO', 'BYE'), CONCAT('GOOD','BAD') FROM DUAL;
SELECT CONCAT('GOOD','BAD') AS "CONCAT", 'GOOD'||'BAD' AS OPERATORS FROM DUAL;

--INITCAP
SELECT INITCAP('good morning!') FROM DUAL;

--LOWER, UPPER
SELECT LOWER('GOOD'), UPPER('good') FROM DUAL;

--LPAD
SELECT LPAD('GOOD', 6) "LPAD1", LPAD('good', 7, '#') AS LPAD2, LPAD('good', 8, 'L') AS LPAD3 FROM DUAL;

--RPAD
SELECT RPAD('GOOD', 6) "RPAD1", RPAD('good', 7, '#') AS RPAD2, RPAD('good', 8, 'L') AS RPAD3 FROM DUAL;

--LTRIM
SELECT LTRIM('GOODBYE' , 'G'), LTRIM('GOODBYE', 'O'), LTRIM('GOGOGGGGDBYE','GO') FROM DUAL;

--RTRIM
SELECT RTRIM('GOODBYE', 'E'), RTRIM('GOODBYE', 'I'), RTRIM('GOODBYE', 'YE') FROM DUAL;

--SUBSTR
SELECT SUBSTR('GOOD MORNING', 1, 4) FROM DUAL;
SELECT SUBSTR('GOOD MORNING', 8, 4) FROM DUAL;

--REPLACE
SELECT REPLACE('GOOD MORNING TOM', 'MORNING', 'EVENING') FROM DUAL;

--TRANSLATE
SELECT REPLACE('YOU ARE NOT ALONE', 'YOU','WE') , TRANSLATE('YOU ARE NOT ALONE UUU', 'YOU', 'WEI') FROM DUAL;

--SYSDATE
SELECT SYSDATE FROM DUAL;

--ADD_MONTHS
SELECT ADD_MONTHS(SYSDATE, 2) FROM DUAL;

--LAST_DAY()
SELECT LAST_DAY(SYSDATE) FROM DUAL;

SELECT SYSDATE + 1 FROM DUAL;
SELECT SYSDATE + (INTERVAL '1' YEAR) FROM DUAL;
SELECT SYSDATE + (INTERVAL '1' MONTH) FROM DUAL;
SELECT SYSDATE + (INTERVAL '1' DAY) FROM DUAL;
SELECT SYSDATE + (INTERVAL '1' HOUR) FROM DUAL;
SELECT SYSDATE + (INTERVAL '1' MINUTE) FROM DUAL;
SELECT SYSDATE + (INTERVAL '1' SECOND) FROM DUAL;

--TO_CHAR
SELECT TO_CHAR(SYSDATE, 'YYYY/MM/DD'), TO_CHAR(SYSDATE, 'YYYY-MM-DD') FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'YYYY/MM/DD HH24:MI:SS'), TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') FROM DUAL;

--TO_DATE
SELECT TO_DATE('2015-03-04', 'YYYY/MM/DD') FROM DUAL;