/* JOIN */
SELECT * FROM EMPLOYEES E;
SELECT * FROM DEPARTMENTS D;

--위 두 테이블을 INNER JOIN
SELECT * FROM EMPLOYEES E INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID ;

SELECT * FROM DEPARTMENTS D;
SELECT * FROM LOCATIONS L;

--위 두 테이블 JOIN
SELECT D.DEPARTMENT_ID , D.DEPARTMENT_NAME , L.CITY FROM DEPARTMENTS D INNER JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID ;

--EMPLOYEES, DEPARTMENTS, LOCATIONS 세 개 JOIN하기
SELECT E.FIRST_NAME , E.LAST_NAME , E.DEPARTMENT_ID , D.DEPARTMENT_NAME , D.LOCATION_ID , L.CITY , J.JOB_TITLE FROM EMPLOYEES E 
INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
INNER JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID 
INNER JOIN JOBS J ON E.JOB_ID = J.JOB_ID 
WHERE L.CITY = 'Seattle' ;


/* LEFT OUTER , RIGHT OUTER JOIN */
SELECT * FROM EMPLOYEES E;
SELECT * FROM JOB_HISTORY J;
SELECT E.EMPLOYEE_ID , E.FIRST_NAME , E.HIRE_DATE , J.START_DATE , J.END_DATE , J.JOB_ID , J.DEPARTMENT_ID 
FROM EMPLOYEES E LEFT OUTER JOIN JOB_HISTORY J ON E.EMPLOYEE_ID = J.EMPLOYEE_ID 
WHERE E.EMPLOYEE_ID =200; 


SELECT * FROM EMPLOYEES E;
SELECT * FROM JOB_HISTORY J;
SELECT E.EMPLOYEE_ID , E.FIRST_NAME , E.HIRE_DATE , J.START_DATE , J.END_DATE , J.JOB_ID , J.DEPARTMENT_ID 
FROM EMPLOYEES E LEFT OUTER JOIN JOB_HISTORY J ON E.EMPLOYEE_ID = J.EMPLOYEE_ID ; 

--QUIZ #1 : 사원들의 이름, 부서번호, 부서명을 출력

SELECT E.FIRST_NAME || ' ' || E.LAST_NAME AS "NAME", E.DEPARTMENT_ID , D.DEPARTMENT_NAME 
FROM EMPLOYEES E INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID ;